name: openhab
version: "2.0.0.b4-1"
summary: openhab 2.0 smart home server
description: |
 openHAB - a vendor and technology agnostic open source automation software for your home.
confinement: strict

apps:
    openhab:
        command: openhab-control
        stop-command: openhab-control stop
        daemon: simple
        restart-condition: always
        plugs: [home, network, network-bind]

    start:
        command: openhab-control
        plugs: [home, network, network-bind]

    clean:
        command: openhab-control clean
        plugs: [home, network, network-bind]

    debug:
        command: openhab-control debug
        plugs: [home, network, network-bind]

    status:
        command: openhab-control status
        plugs: [home, network, network-bind]

    stop:
        command: openhab-control stop
        plugs: [home, network, network-bind]

    console:
        command: openhab-control console
        plugs: [home, network, network-bind]

    client:
        command: openhab-control client
        plugs: [home, network, network-bind]

parts:
    openhab:
        source: https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-offline%2F2.0.0.b4%2Fopenhab-offline-2.0.0.b4.tar.gz
        plugin: openhab
        stage-packages: [openjdk-8-jre]
        stage:
          - -start*.bat
          - -runtime/karaf/bin/*.bat
        snap:
          - -start*.bat
          - -runtime/karaf/bin/*.bat

    openhab-control:
        source: .
        plugin: dump
        organize:
            openhab-control: bin/openhab-control
