name: openhab
version: "2.0.0.b4-2-offline"
summary: openhab 2.0 smart home server, offline versions
description: |
 openHAB - a vendor and technology agnostic open source automation software for your home.
 offline version has all officially supported modules bundled

confinement: strict
grade: devel

apps:
    openhab:
        command: openhab-control
        stop-command: openhab-control stop
        daemon: simple
        restart-condition: always
        plugs: [home, network, network-bind]

    start:
        command: openhab-control
        plugs: [home, network, network-bind]

    clean:
        command: openhab-control clean
        plugs: [home, network, network-bind]

    debug:
        command: openhab-control debug
        plugs: [home, network, network-bind]

    status:
        command: openhab-control status
        plugs: [home, network, network-bind]

    stop:
        command: openhab-control stop
        plugs: [home, network, network-bind]

    console:
        command: openhab-control console
        plugs: [home, network, network-bind, process-control]

    client:
        command: openhab-control client
        plugs: [home, network, network-bind]

parts:
    openhab:
        source: https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-offline%2F2.0.0.b4%2Fopenhab-offline-2.0.0.b4.tar.gz
        plugin: openhab
        stage:
          - -start*
          - -runtime/karaf/bin/*.bat
        snap:
          - -start*
          - -runtime/karaf/bin/*.bat

    jre:
        source: .
        plugin: dump
        stage-packages: [openjdk-8-jre]
        filesets:
          binaries:
            - -lib
            - -var
            - -usr/include
            - -usr/lib/gcc
            - -usr/lib/ssl
            - -usr/lib/X11
            - -usr/lib/*-linux-gnu/
            - -usr/sbin
            - -usr/shared
        stage:
          - $binaries
        snap:
          - $binaries

    openhab-control:
        source: .
        plugin: dump
        organize:
            openhab-control: bin/openhab-control

    # helper script to cponnect interfaces
    connect-interfaces:
        source: .
        plugin: dump
        organize:
            connect-interfaces: bin/connect-interfaces
