name: openhab
version: "2.0.0.b4-1"
summary: openhab 2.0 smart home server
description: |
 openHAB - a vendor and technology agnostic open source automation software for your home.

confinement: devmode
grade: devel

apps:
    openhab:
        command: openhab-control
        plugs: [home, network, network-bind]

    start:
        command: openhab-control
        plugs: [home, network, network-bind]

    clean:
        command: openhab-control clean
        plugs: [home, network, network-bind]

    debug:
        command: openhab-control debug
        plugs: [home, network, network-bind]

    status:
        command: openhab-control status
        plugs: [home, network, network-bind]

    stop:
        command: openhab-control stop
        plugs: [home, network, network-bind]

    console:
        command: openhab-control console
        plugs: [home, network, network-bind]

    client:
        command: openhab-control client
        plugs: [home, network, network-bind]

parts:
    openhab:
        source: https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-online%2F2.0.0.b4%2Fopenhab-online-2.0.0.b4.tar.gz
        plugin: openhab
        stage:
          - -start*
          - -runtime/karaf/bin/*.bat
        snap:
          - -start*
          - -runtime/karaf/bin/*.bat

    jre:
        source: .
        plugin: dump
        stage-packages: [openjdk-8-jre]
        organize:
          usr/lib/jvm/java-8-openjdk-*: jdk
        filesets:
          binaries:
            - -etc
            - -lib
            - -usr/lib
            - -usr
            - -var
        stage:
          - $binaries
        snap:
          - $binaries

    openhab-control:
        source: .
        plugin: dump
        organize:
            openhab-control: bin/openhab-control
